### ISSUE TITLE
Running and installing as non-root

### ISSUE THREAD

**Issue by iljah** [vsoch/helpme#18]
I haven't used docker before but apparently it must be run as root which seems like a very insecure way of running "random" packages downloaded from github. At minimum I think dockerfile should create a helpme user or similar and switch to that user before executing, as detailed e.g. at http://www.projectatomic.io/docs/docker-image-author-guidance/

An even better approach would be to allow installation with pip. I tried that and it seemed to work but when running helpme I get: `ModuleNotFoundError: No module named 'asciinema'`. Missing dependency perhaps?

**Comment by vsoch** [comment]
I can't help much with how Docker works, other than suggesting that a Singularity container is used (doesn't require sudo). The user can always choose to install the tool locally.

Good catch on the missing dependency! I just hit this too :) I had put it in the requirements.txt, but not in the setup.py --> version.py. I just added it and will merge soon.

**Comment by vsoch** [comment]
okay, merged! The docker image (with these changes) is also rebuilding.
