### ISSUE TITLE
HelpMe Github Issue: stanky-animal-1562

### ISSUE THREAD

**Issue by rougier** [vsoch/helpme#24]
test
## Environment
 - **LANG**: C.UTF-8
 - **PWD**: /code
 - **HOME**: /root
 - **TERM**: xterm
 - **PATH**: /opt/conda/bin:/usr/local/bin:/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

generated by [HelpMe](https://vsoch.github.io/helpme/)

**Comment by vsoch** [comment]
haha, "stanky-animal"

I get immense pleasure out of the silly name generator every time :)

**Comment by rougier** [comment]
By they way, you might want to give user the opportunity to set the title and/or use a more neutral title (I just imagine having such an issue opened in one of my project, not sure I would pay big attention to it).

**Comment by vsoch** [comment]
This is a great idea! See #28 and #26
