### ISSUE TITLE
HelpMe Github Issue: muffled-sundae-3540

### ISSUE THREAD

**Issue by iljah** [vsoch/helpme#26]
testing submitting issue
generated by [HelpMe](https://vsoch.github.io/helpme/)

**Comment by iljah** [comment]
Hmm yeah I think it would be better if helpme asked for a title or short description that could be used instead of random words and numbers...

**Comment by vsoch** [comment]
Agreed! I'm on it.

**Comment by vsoch** [comment]
muffled sundae :)

**Comment by vsoch** [comment]
okay I have added the ability to specify a title! See the test issue here:

https://github.com/vsoch/helpme/issues/29

The really cool part is that adding this field came down to just customizing the default config for Github, from this:

```bash
[github]
user_message_welcome = Hello Friend! I'll help you post a Github issue today.
user_prompt_repo = What is the Github repository to post to? (e.g., username/reponame)
user_prompt_issue = Please describe the issue you are having 
record_asciinema = True
record_environment = True
```

to this!

```bash
[github]
user_message_welcome = Hello Friend! I'll help you post a Github issue today.
user_prompt_repo = What is the Github repository to post to? (e.g., username/reponame)
user_prompt_issue = Please describe the issue you are having 
user_prompt_title = Please provide a meaningful title for your issue
record_asciinema = True
record_environment = True
```
I'm going to look at your other posted issues and I'll have this fix added in with other fixes per your suggestions in the other issues. stay tuned!
