### ISSUE TITLE
Automatic testing?

### ISSUE THREAD

**Issue by iljah** [vsoch/helpme#27]
Is it possible to write automatic tests for helpme? For example could you create a dummy repository/github account and create a token with access to public repositories so that running helpme test would submit a new issue to that dummy repository and afterwards verify that it exists?

**Comment by iljah** [comment]
Naturally above token would be default that everyone start with unless they override it with HELPME_GITHUB_TOKEN. Not sure whether that would be secure or private but at least you'd know when people run helpme test :)

**Comment by vsoch** [comment]
I've thought about this and I'm not sure it's possible to create some dummy token - tokens are always linked to a user account and I'm not even super comfortable with having them on Travis or Circle with encryption. What I can do is try to write simple tests for the different components (without testing the actual API submission). Would this be useful do you think?

**Comment by vsoch** [comment]
Or did you moreso have in mind a "helpme test" that would test the endpoint for the user?

**Comment by iljah** [comment]
Not a dummy token then but a dummy github account. That might be against github terms of service anyway. Since helpme has two commands at the moment I think regular usage instructions/examples are fine, it should be apparent if something doesn't work.
