### ISSUE TITLE
Discourse plugin?

### ISSUE THREAD

**Issue by vsoch** [vsoch/helpme#32]
https://docs.discourse.org/

**Comment by mih** [comment]
This seems like a great way for an application like DataLad (http://datalad.org) to offer users a way to get support. Thanks much for implementing it!

For us, and many other neuro* projects it would be very useful to have a helper plugin for the Q&A site Neurostars (https://neurostars.org) -- which I think is running discourse.

So +1 from me!

**Comment by vsoch** [comment]
Awesome! I'll look into this again later today :) Having some fun with Github actions right now!

**Comment by vsoch** [comment]
Ha, this is too good to not share :)

![image](https://user-images.githubusercontent.com/814322/49456955-f073d900-f7b7-11e8-9211-e42b16ef52e2.png)

reverse engineer... away!

**Comment by vsoch** [comment]
hey @mih I'm all done! Documentation (via PDF that will render to the web interface on deployment) and instructions for testing are here --> https://github.com/vsoch/helpme/pull/33 Would you care to test if/when you have some time?

**Comment by mih** [comment]
Thanks much! Will look into it. Emailed you re possible real-world test.

**Comment by vsoch** [comment]
Yes, and just responded! I'm hoping to get it tested with AskCI too.
