### ISSUE TITLE
logo

### ISSUE THREAD

**Issue by pdurbin** [vsoch/helpme#46]
Over in #45 @vsoch said she doesn't have a logo for helpme. Perhaps we could post a job at https://discourse.opensourcedesign.net/c/job-postings using their "post a job" form at https://opensourcedesign.net/jobs/

**Comment by vsoch** [comment]
Actually now that I'm looking at it, we sort of do? This simple green paper:

https://vsoch.github.io/helpme/assets/img/helpme.png

Is it terrible? I made it in gimp, heh.

**Comment by pdurbin** [comment]
It's a good start! Logos can change! Ship it!

**Comment by vsoch** [comment]
Haha, okay :)

https://github.com/vsoch/helpme

**Comment by pdurbin** [comment]
Looks great!
